# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ewaste_service_pb2 as ewaste__service__pb2


class EwasteServiceStub(object):
    """The eWaste service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddEwaste = channel.unary_unary(
                '/ewaste.EwasteService/AddEwaste',
                request_serializer=ewaste__service__pb2.AddEwasteRequest.SerializeToString,
                response_deserializer=ewaste__service__pb2.AddEwasteResponse.FromString,
                )
        self.GetUserEwaste = channel.unary_unary(
                '/ewaste.EwasteService/GetUserEwaste',
                request_serializer=ewaste__service__pb2.GetUserEwasteRequest.SerializeToString,
                response_deserializer=ewaste__service__pb2.GetUserEwasteResponse.FromString,
                )
        self.GetUserEwasteStats = channel.unary_unary(
                '/ewaste.EwasteService/GetUserEwasteStats',
                request_serializer=ewaste__service__pb2.GetUserEwasteStatsRequest.SerializeToString,
                response_deserializer=ewaste__service__pb2.GetUserEwasteStatsResponse.FromString,
                )
        self.GetEwasteItem = channel.unary_unary(
                '/ewaste.EwasteService/GetEwasteItem',
                request_serializer=ewaste__service__pb2.GetEwasteItemRequest.SerializeToString,
                response_deserializer=ewaste__service__pb2.GetEwasteItemResponse.FromString,
                )


class EwasteServiceServicer(object):
    """The eWaste service definition.
    """

    def AddEwaste(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserEwaste(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserEwasteStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEwasteItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EwasteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddEwaste': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEwaste,
                    request_deserializer=ewaste__service__pb2.AddEwasteRequest.FromString,
                    response_serializer=ewaste__service__pb2.AddEwasteResponse.SerializeToString,
            ),
            'GetUserEwaste': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserEwaste,
                    request_deserializer=ewaste__service__pb2.GetUserEwasteRequest.FromString,
                    response_serializer=ewaste__service__pb2.GetUserEwasteResponse.SerializeToString,
            ),
            'GetUserEwasteStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserEwasteStats,
                    request_deserializer=ewaste__service__pb2.GetUserEwasteStatsRequest.FromString,
                    response_serializer=ewaste__service__pb2.GetUserEwasteStatsResponse.SerializeToString,
            ),
            'GetEwasteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEwasteItem,
                    request_deserializer=ewaste__service__pb2.GetEwasteItemRequest.FromString,
                    response_serializer=ewaste__service__pb2.GetEwasteItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ewaste.EwasteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EwasteService(object):
    """The eWaste service definition.
    """

    @staticmethod
    def AddEwaste(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ewaste.EwasteService/AddEwaste',
            ewaste__service__pb2.AddEwasteRequest.SerializeToString,
            ewaste__service__pb2.AddEwasteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserEwaste(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ewaste.EwasteService/GetUserEwaste',
            ewaste__service__pb2.GetUserEwasteRequest.SerializeToString,
            ewaste__service__pb2.GetUserEwasteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserEwasteStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ewaste.EwasteService/GetUserEwasteStats',
            ewaste__service__pb2.GetUserEwasteStatsRequest.SerializeToString,
            ewaste__service__pb2.GetUserEwasteStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEwasteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ewaste.EwasteService/GetEwasteItem',
            ewaste__service__pb2.GetEwasteItemRequest.SerializeToString,
            ewaste__service__pb2.GetEwasteItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
