# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rewards_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15rewards_service.proto\x12\x07rewards\"9\n\x10\x41\x64\x64PointsRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x13\n\x0bpointsToAdd\x18\x02 \x01(\x05\"5\n\x11\x41\x64\x64PointsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\")\n\x15GetUserRewardsRequest\x12\x10\n\x08username\x18\x01 \x01(\t\":\n\x16GetUserRewardsResponse\x12 \n\x07rewards\x18\x01 \x03(\x0b\x32\x0f.rewards.Reward\"9\n\x13RedeemRewardRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08rewardId\x18\x02 \x01(\x05\"8\n\x14RedeemRewardResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"D\n\x06Reward\x12\x10\n\x08rewardId\x18\x01 \x01(\x05\x12\x12\n\nrewardName\x18\x02 \x01(\t\x12\x14\n\x0crewardPoints\x18\x03 \x01(\x05\"\x13\n\x11GetRewardsRequest\"6\n\x12GetRewardsResponse\x12 \n\x07rewards\x18\x01 \x03(\x0b\x32\x0f.rewards.Reward\"(\n\x14GetUserPointsRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\'\n\x15GetUserPointsResponse\x12\x0e\n\x06points\x18\x01 \x01(\x05\x32\x8a\x03\n\rRewardService\x12\x42\n\tAddPoints\x12\x19.rewards.AddPointsRequest\x1a\x1a.rewards.AddPointsResponse\x12\x45\n\nGetRewards\x12\x1a.rewards.GetRewardsRequest\x1a\x1b.rewards.GetRewardsResponse\x12Q\n\x0eGetUserRewards\x12\x1e.rewards.GetUserRewardsRequest\x1a\x1f.rewards.GetUserRewardsResponse\x12N\n\rGetUserPoints\x12\x1d.rewards.GetUserPointsRequest\x1a\x1e.rewards.GetUserPointsResponse\x12K\n\x0cRedeemReward\x12\x1c.rewards.RedeemRewardRequest\x1a\x1d.rewards.RedeemRewardResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rewards_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDPOINTSREQUEST._serialized_start=34
  _ADDPOINTSREQUEST._serialized_end=91
  _ADDPOINTSRESPONSE._serialized_start=93
  _ADDPOINTSRESPONSE._serialized_end=146
  _GETUSERREWARDSREQUEST._serialized_start=148
  _GETUSERREWARDSREQUEST._serialized_end=189
  _GETUSERREWARDSRESPONSE._serialized_start=191
  _GETUSERREWARDSRESPONSE._serialized_end=249
  _REDEEMREWARDREQUEST._serialized_start=251
  _REDEEMREWARDREQUEST._serialized_end=308
  _REDEEMREWARDRESPONSE._serialized_start=310
  _REDEEMREWARDRESPONSE._serialized_end=366
  _REWARD._serialized_start=368
  _REWARD._serialized_end=436
  _GETREWARDSREQUEST._serialized_start=438
  _GETREWARDSREQUEST._serialized_end=457
  _GETREWARDSRESPONSE._serialized_start=459
  _GETREWARDSRESPONSE._serialized_end=513
  _GETUSERPOINTSREQUEST._serialized_start=515
  _GETUSERPOINTSREQUEST._serialized_end=555
  _GETUSERPOINTSRESPONSE._serialized_start=557
  _GETUSERPOINTSRESPONSE._serialized_end=596
  _REWARDSERVICE._serialized_start=599
  _REWARDSERVICE._serialized_end=993
# @@protoc_insertion_point(module_scope)
