apiVersion: apps/v1
kind: Deployment
metadata:
  name: rewards-ewaste
  labels:
    app: rewards-ewaste
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rewards-ewaste
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: rewards-ewaste
    spec:
      containers:
        - name: rewards-ewaste
          image: shunyaoteo99/rewards_ewaste
          ports:
            - containerPort: 50052
          env:
            - name: MYSQL_USER
              value: eWaste_user
            - name: MYSQL_DATABASE
              value: rewards_eWaste
          envFrom:
            - configMapRef:
                name: rewards-configmap
            - secretRef:
                name: rewards-secret