# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ewaste_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65waste_service.proto\x12\x06\x65waste\"H\n\x10\x41\x64\x64\x45wasteRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x11\n\titem_type\x18\x02 \x01(\t\x12\x0e\n\x06weight\x18\x03 \x01(\x02\"5\n\x11\x41\x64\x64\x45wasteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\")\n\x14GetUserEwasteRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\":\n\x15GetUserEwasteResponse\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.ewaste.EwasteItem\".\n\x19GetUserEwasteStatsRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\"\xaa\x01\n\x1aGetUserEwasteStatsResponse\x12\x45\n\nitem_stats\x18\x01 \x03(\x0b\x32\x31.ewaste.GetUserEwasteStatsResponse.ItemStatsEntry\x1a\x45\n\x0eItemStatsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.ewaste.EwasteStats:\x02\x38\x01\"\'\n\x14GetEwasteItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\"9\n\x15GetEwasteItemResponse\x12 \n\x04item\x18\x01 \x01(\x0b\x32\x12.ewaste.EwasteItem\"g\n\nEwasteItem\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x11\n\titem_type\x18\x03 \x01(\t\x12\x0e\n\x06weight\x18\x04 \x01(\x02\x12\x12\n\ndate_added\x18\x05 \x01(\t\"8\n\x0b\x45wasteStats\x12\x14\n\x0ctotal_weight\x18\x01 \x01(\x02\x12\x13\n\x0btotal_items\x18\x02 \x01(\x05\x32\xd2\x02\n\rEwasteService\x12\x42\n\tAddEwaste\x12\x18.ewaste.AddEwasteRequest\x1a\x19.ewaste.AddEwasteResponse\"\x00\x12N\n\rGetUserEwaste\x12\x1c.ewaste.GetUserEwasteRequest\x1a\x1d.ewaste.GetUserEwasteResponse\"\x00\x12]\n\x12GetUserEwasteStats\x12!.ewaste.GetUserEwasteStatsRequest\x1a\".ewaste.GetUserEwasteStatsResponse\"\x00\x12N\n\rGetEwasteItem\x12\x1c.ewaste.GetEwasteItemRequest\x1a\x1d.ewaste.GetEwasteItemResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ewaste_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETUSEREWASTESTATSRESPONSE_ITEMSTATSENTRY._options = None
  _GETUSEREWASTESTATSRESPONSE_ITEMSTATSENTRY._serialized_options = b'8\001'
  _ADDEWASTEREQUEST._serialized_start=32
  _ADDEWASTEREQUEST._serialized_end=104
  _ADDEWASTERESPONSE._serialized_start=106
  _ADDEWASTERESPONSE._serialized_end=159
  _GETUSEREWASTEREQUEST._serialized_start=161
  _GETUSEREWASTEREQUEST._serialized_end=202
  _GETUSEREWASTERESPONSE._serialized_start=204
  _GETUSEREWASTERESPONSE._serialized_end=262
  _GETUSEREWASTESTATSREQUEST._serialized_start=264
  _GETUSEREWASTESTATSREQUEST._serialized_end=310
  _GETUSEREWASTESTATSRESPONSE._serialized_start=313
  _GETUSEREWASTESTATSRESPONSE._serialized_end=483
  _GETUSEREWASTESTATSRESPONSE_ITEMSTATSENTRY._serialized_start=414
  _GETUSEREWASTESTATSRESPONSE_ITEMSTATSENTRY._serialized_end=483
  _GETEWASTEITEMREQUEST._serialized_start=485
  _GETEWASTEITEMREQUEST._serialized_end=524
  _GETEWASTEITEMRESPONSE._serialized_start=526
  _GETEWASTEITEMRESPONSE._serialized_end=583
  _EWASTEITEM._serialized_start=585
  _EWASTEITEM._serialized_end=688
  _EWASTESTATS._serialized_start=690
  _EWASTESTATS._serialized_end=746
  _EWASTESERVICE._serialized_start=749
  _EWASTESERVICE._serialized_end=1087
# @@protoc_insertion_point(module_scope)
